# Generated by Django 4.2.3 on 2023-08-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='Url',
            new_name='url',
        ),
    ]
